import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getDashboardStats } from "../services/adminService.js";
import { formatDate } from "../utils/dateUtils.js";
function StatCard({label,value,note,className=""}){return <div className={`admin-stat-card ${className}`}><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
function StatusPill({status}){return <span className={`admin-status-pill admin-status-pill--${status.toLowerCase()}`}>{status}</span>}
export default function AdminDashboardPage(){
 const [data,setData]=useState(null),[status,setStatus]=useState("loading"),[error,setError]=useState("");
 const load=async()=>{setStatus("loading");setError("");try{setData(await getDashboardStats());setStatus("ready")}catch(err){setStatus("error");setError(err.response?.data?.message||"Unable to load dashboard data.")}};
 useEffect(()=>{load()},[]);
 if(status==="loading") return <div className="admin-content"><div className="admin-page-title"><div><p>Overview</p><h1>Dashboard</h1></div></div><div className="state-panel"><p className="state-panel__title">Loading dashboard…</p></div></div>;
 if(status==="error") return <div className="admin-content"><div className="admin-page-title"><div><p>Overview</p><h1>Dashboard</h1></div></div><div className="state-panel state-panel--error"><p className="state-panel__title">Couldn’t load dashboard</p><p className="state-panel__body">{error}</p><button className="button button--primary" onClick={load}>Retry</button></div></div>;
 return <div className="admin-content"><div className="admin-page-title"><div><p>Overview</p><h1>Dashboard</h1></div><button className="admin-refresh" onClick={load}>↻ Refresh</button></div>
  <div className="admin-stat-grid"><StatCard label="Total Equipment" value={data.totalEquipment} note="In catalog"/><StatCard label="Available Now" value={data.availableEquipment} note="Ready to rent" className="admin-stat-card--success"/><StatCard label="Active Rentals" value={data.activeRentals} note="Currently in use"/><StatCard label="Total Bookings" value={data.totalBookings} note="All time"/></div>
  <div className="admin-grid-2"><section className="admin-panel"><div className="admin-panel__header"><div><p>Booking activity</p><h2>Status overview</h2></div></div><div className="status-overview"><div><span className="status-overview__dot status-overview__dot--pending"/><strong>{data.pendingBookings}</strong><span>Pending</span></div><div><span className="status-overview__dot status-overview__dot--confirmed"/><strong>{data.confirmedBookings}</strong><span>Confirmed</span></div><div><span className="status-overview__dot status-overview__dot--completed"/><strong>{data.completedBookings}</strong><span>Completed</span></div></div><div className="admin-value-row"><span>Total booking value</span><strong>₹{Number(data.totalBookingValue).toLocaleString("en-IN")}</strong></div></section>
  <section className="admin-panel"><div className="admin-panel__header"><div><p>Equipment</p><h2>Current availability</h2></div></div><div className="equipment-status-list">{data.equipmentStatus.map(item=><div className="equipment-status-row" key={item._id}><div><strong>{item.name}</strong><span>{item.category}</span></div><span className={`admin-status-pill ${item.availability?"admin-status-pill--available":"admin-status-pill--rented"}`}>{item.availability?"Available":item.activeRental?"Rented":"Unavailable"}</span></div>)}</div></section></div>
  <section className="admin-panel admin-panel--table"><div className="admin-panel__header"><div><p>Latest activity</p><h2>Recent bookings</h2></div><Link to="/admin/bookings" className="admin-panel__link">View all bookings →</Link></div>{data.recentBookings.length===0?<div className="admin-empty">No bookings have been submitted yet.</div>:<div className="admin-recent-table-wrap"><table className="admin-recent-table"><thead><tr><th>Booking</th><th>Customer</th><th>Equipment</th><th>Dates</th><th>Value</th><th>Status</th></tr></thead><tbody>{data.recentBookings.map(b=><tr key={b._id}><td className="booking-table__id">#{b._id.slice(-8).toUpperCase()}</td><td>{b.customerName}</td><td>{b.equipment?.name||"—"}</td><td>{formatDate(b.startDate)} – {formatDate(b.endDate)}</td><td>₹{Number(b.totalCost).toLocaleString("en-IN")}</td><td><StatusPill status={b.status}/></td></tr>)}</tbody></table></div>}</section>
 </div>;
}
