import { useState } from "react";
import { Navigate, useLocation, useNavigate } from "react-router-dom";
import { adminLogin, isAdminAuthenticated } from "../services/authService.js";
export default function AdminLoginPage() {
  const navigate=useNavigate(), location=useLocation(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState("");
  if (isAdminAuthenticated()) return <Navigate to="/admin/dashboard" replace />;
  const submit=async(e)=>{e.preventDefault();setError("");if(!email.trim()||!password){setError("Enter your administrator email and password.");return;}setSubmitting(true);try{await adminLogin(email.trim(),password);navigate(location.state?.from||"/admin/dashboard",{replace:true});}catch(err){setError(err.response?.data?.message||"Unable to sign in. Please check your credentials.");}finally{setSubmitting(false);}};
  return <div className="admin-login-page"><div className="admin-login-card"><div className="admin-login-card__mark">A</div><p className="admin-login-card__eyebrow">ADMINISTRATOR PORTAL</p><h1>Sign in to manage rentals</h1><p className="admin-login-card__subtitle">Access bookings, equipment status and rental activity.</p>{error&&<div className="form-banner form-banner--error">{error}</div>}<form onSubmit={submit} className="admin-login-form"><label className="form-field__label" htmlFor="admin-email">Email</label><input id="admin-email" type="email" className="form-field__input" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" /><label className="form-field__label" htmlFor="admin-password">Password</label><input id="admin-password" type="password" className="form-field__input" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" /><button className="submit-button" type="submit" disabled={submitting}>{submitting?"Signing in…":"Sign In"}</button></form><a className="admin-login-back" href="/">← Back to public catalog</a></div></div>;
}
